spring:
  application:
    name: leanRecipes

  datasource:
#    url: jdbc:postgresql://localhost:5432/lean-recipes
#    url: jdbc:postgresql://localhost:5432/postgres
#    FOR PRODUCTION
#    url: jdbc:postgresql://database:5432/lean-recipes-db
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: 12345

    hikari:
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect



#  spring.datasource.url=jdbc:postgresql://database:5432/lean-recipes-db
#  spring.datasource.username=postgres
#  spring.datasource.password=12345


