spring:
  application:
    name: leanRecipes

  datasource:
#    url: jdbc:postgresql://localhost:5432/lean-recipes
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
